name: Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zstandard numpy xxhash customtkinter pyyaml mmh3 pyinstaller
        
    - name: Build Windows executables
      run: |
        pyinstaller --onefile "src\lite.py" --icon="images/restbl.ico" --add-data "checksums/checksums.bin;checksums/" --add-data "images/restbl.ico;images/" --add-data "restbl/*.json;restbl/" --add-data "dic/zsdic;dic/" --add-data "string_lists/*.txt;string_lists/"
        pyinstaller --onefile "src\restbl.py" --icon="images/restbl.ico" --add-data "checksums/checksums.bin;checksums/" --add-data "images/restbl.ico;images/" --add-data "restbl/*.json;restbl/" --add-data "dic/zsdic;dic/" --add-data "string_lists/*.txt;string_lists/"
        
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-builds
        path: |
          dist/lite.exe
          dist/restbl.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zstandard numpy xxhash customtkinter pyyaml mmh3 pyinstaller
        
    - name: Build Linux executables
      run: |
        pyinstaller --onefile "src/lite.py" --add-data="checksums/checksums.bin:checksums/" --add-data="restbl/*.json:restbl/" --add-data="string_lists/*.txt:string_lists/" --add-data="dic/zsdic:dic/" --add-data="images/restbl.png:images/"
        pyinstaller --onefile "src/restbl.py" --add-data="checksums/checksums.bin:checksums/" --add-data="restbl/*.json:restbl/" --add-data="string_lists/*.txt:string_lists/" --add-data="dic/zsdic:dic/" --add-data="images/restbl.png:images/"
        
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-builds
        path: |
          dist/lite
          dist/restbl 