name: Build

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip uninstall PySimpleGUI -y
        python -m pip cache purge
        python -m pip install --force-reinstall --extra-index-url https://PySimpleGUI.net/install PySimpleGUI
        python -m pip install -r requirements.txt
        pip install zstandard numpy xxhash customtkinter pyyaml mmh3 pyinstaller
        
    - name: Build Windows executables
      run: |
        pyinstaller --onefile "src\lite.py" --icon="images/restbl.ico" --add-data "checksums/checksums.bin;checksums/" --add-data "images/restbl.ico;images/" --add-data "restbl/*.json;restbl/" --add-data "dic/zsdic;dic/" --add-data "string_lists/*.txt;string_lists/"
        pyinstaller --onefile "src\restbl.py" --icon="images/restbl.ico" --add-data "checksums/checksums.bin;checksums/" --add-data "images/restbl.ico;images/" --add-data "restbl/*.json;restbl/" --add-data "dic/zsdic;dic/" --add-data "string_lists/*.txt;string_lists/"
        
    - name: Create Windows archives
      run: |
        cd dist
        7z a "RESTBL-Lite-${{ github.event.release.tag_name }}-Windows-x64.zip" "lite.exe"
        7z a "RESTBL-${{ github.event.release.tag_name }}-Windows-x64.zip" "restbl.exe"
        move *.zip ..
        cd ..
        
    - name: Upload Windows release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          RESTBL-Lite-${{ github.event.release.tag_name }}-Windows-x64.zip
          RESTBL-${{ github.event.release.tag_name }}-Windows-x64.zip
        token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip uninstall PySimpleGUI -y
        python -m pip cache purge
        python -m pip install --force-reinstall --extra-index-url https://PySimpleGUI.net/install PySimpleGUI
        python -m pip install -r requirements.txt
        pip install zstandard numpy xxhash customtkinter pyyaml mmh3 pyinstaller
        
    - name: Build Linux executables
      run: |
        pyinstaller --onefile "src/lite.py" --add-data="checksums/checksums.bin:checksums/" --add-data="restbl/*.json:restbl/" --add-data="string_lists/*.txt:string_lists/" --add-data="dic/zsdic:dic/" --add-data="images/restbl.png:images/"
        pyinstaller --onefile "src/restbl.py" --add-data="checksums/checksums.bin:checksums/" --add-data="restbl/*.json:restbl/" --add-data="string_lists/*.txt:string_lists/" --add-data="dic/zsdic:dic/" --add-data="images/restbl.png:images/"
        
    - name: Create Linux archives
      run: |
        cd dist
        zip "RESTBL-Lite-${{ github.event.release.tag_name }}-Linux-x64.zip" "lite"
        zip "RESTBL-${{ github.event.release.tag_name }}-Linux-x64.zip" "restbl"
        mv *.zip ..
        cd ..
        
    - name: Upload Linux release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          RESTBL-Lite-${{ github.event.release.tag_name }}-Linux-x64.zip
          RESTBL-${{ github.event.release.tag_name }}-Linux-x64.zip
        token: ${{ secrets.GITHUB_TOKEN }} 